In [86]:
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [87]:
df = pd.read_json("exps.jsonl", lines=True)
print(len(df))
df.head()

10

,id,name,params.dataset.path,params.dataset.name,params.dataset.split,params.qa.model,params.qa.temperature,params.qa.system_prompt,params.qa.user_prompt_template,params.qa.few_shot_examples,...,metrics.gen_token_count.success.max,metrics.gen_token_count.fail.count,metrics.gen_token_count.fail.mean,metrics.gen_token_count.fail.std,metrics.gen_token_count.fail.min,metrics.gen_token_count.fail.25%,metrics.gen_token_count.fail.50%,metrics.gen_token_count.fail.75%,metrics.gen_token_count.fail.max,params.qa.technique
0,698469ea608e3359e23ca7295849e0aca721737e,riant-duad,bdsaglam/musique,answerable,validation,llama-3-70b-tgi,0,cok/adapted.txt,cq.txt,semi/cok.json,...,161,863,82.475087,23.488537,3,67.0,81,96.5,168,COK
1,f6a11e56b2290d8503564757de7bc95211f249c8,lairy-weka,bdsaglam/musique,answerable,validation,llama-3-70b-tgi,0,ccot/format-thought.txt,cq.txt,semi/ccot.json,...,103,2292,16.564136,191.058127,0,0.0,0,4.0,5120,CCOT
2,9ccb840e02fb17eddf61deccfe0a6db45a63c40c,lowly-mesh,bdsaglam/musique,answerable,validation,llama-3-70b-tgi,0,cot/format-thought.txt,cq.txt,semi/cot.json,...,162,768,61.272135,21.961152,6,46.0,58,72.0,140,COT
3,1e4c71b1585d18d4a14578e66d14be874ad78ef2,model-wire,bdsaglam/musique,answerable,validation,llama-3-70b-tgi,0,cte/format-triplets-few.txt,cq.txt,semi/cte.json,...,91,746,48.310992,16.961933,16,37.0,45,56.0,153,CTE
4,00ca4c1383ea6b9b0921e4616fac5b073984a363,heady-yews,bdsaglam/musique,answerable,validation,llama-3-70b-tgi,0,direct/format-few.txt,cq.txt,semi/direct.json,...,26,690,7.726087,9.269645,3,4.0,5,7.0,89,DIRECT

In [88]:
param_cols = [col for col in df.columns if col.startswith("params.")]
metric_cols = [col for col in df.columns if col.startswith("metrics.")]
df.drop(
    columns=[
        "id",
        "params.dataset.path",
        "params.dataset.name",
        "params.dataset.split",
        "params.qa.model",
    ],
    inplace=True,
)

In [89]:
target_param_cols = [
    "params.qa.technique",
    "params.qa.system_prompt",
    "params.qa.few_shot_examples",
    "params.qa.n_shot",
]
df = df.sort_values(target_param_cols + ["params.run"])
df.reset_index(drop=True, inplace=True)
df.head()

,name,params.qa.temperature,params.qa.system_prompt,params.qa.user_prompt_template,params.qa.few_shot_examples,params.qa.n_shot,params.qa.n_sc,params.run,metrics.exact_match,metrics.f1,...,metrics.gen_token_count.success.max,metrics.gen_token_count.fail.count,metrics.gen_token_count.fail.mean,metrics.gen_token_count.fail.std,metrics.gen_token_count.fail.min,metrics.gen_token_count.fail.25%,metrics.gen_token_count.fail.50%,metrics.gen_token_count.fail.75%,metrics.gen_token_count.fail.max,params.qa.technique
0,adust-paws,0,ccot/format-thought.txt,cq.txt,semi/ccot.json,0,1,1,0.591643,0.710493,...,162,700,49.575714,17.156312,19,38.00,47,59.0,187,CCOT
1,lairy-weka,0,ccot/format-thought.txt,cq.txt,semi/ccot.json,3,1,1,0.036409,0.052465,...,103,2292,16.564136,191.058127,0,0.00,0,4.0,5120,CCOT
2,gypsy-feel,0,cok/adapted.txt,cq.txt,semi/cok.json,0,1,1,0.612329,0.725410,...,243,674,102.606825,35.052430,24,78.00,97,118.0,300,COK
3,riant-duad,0,cok/adapted.txt,cq.txt,semi/cok.json,3,1,1,0.547373,0.656394,...,161,863,82.475087,23.488537,3,67.00,81,96.5,168,COK
4,laigh-flex,0,cot/format-thought.txt,cq.txt,semi/cot.json,0,1,1,0.584195,0.706219,...,211,712,65.831461,92.391326,16,46.75,58,72.0,2444,COT

In [91]:
def remove_ext(filename):
    return filename.split(".", 1)[0]


for col in [
    "params.qa.system_prompt",
    "params.qa.user_prompt_template",
    "params.qa.few_shot_examples",
]:
    df[col] = df[col].map(remove_ext)

In [100]:
zero_shot_mask = df["params.qa.n_shot"] == 0

In [103]:
df.loc[zero_shot_mask, target_param_cols + metric_cols[:2]].sort_values('metrics.f1', ascending=False)

,params.qa.technique,params.qa.system_prompt,params.qa.few_shot_examples,params.qa.n_shot,params.qa.n_sc,params.qa.temperature,metrics.exact_match,metrics.f1
2,COK,cok/adapted,semi/cok,0,1,0,0.612329,0.725410
0,CCOT,ccot/format-thought,semi/ccot,0,1,0,0.591643,0.710493
6,CTE,cte/format-triplets-few,semi/cte,0,1,0,0.590401,0.709570
4,COT,cot/format-thought,semi/cot,0,1,0,0.584195,0.706219
8,DIRECT,direct/format-few,semi/direct,0,1,0,0.291684,0.366754

In [104]:
df.loc[~zero_shot_mask, target_param_cols + metric_cols[:2]].sort_values('metrics.f1', ascending=False)

,params.qa.technique,params.qa.system_prompt,params.qa.few_shot_examples,params.qa.n_shot,params.qa.n_sc,params.qa.temperature,metrics.exact_match,metrics.f1
9,DIRECT,direct/format-few,semi/direct,3,1,0,0.603227,0.719669
7,CTE,cte/format-triplets-few,semi/cte,3,1,0,0.582954,0.702151
5,COT,cot/format-thought,semi/cot,3,1,0,0.573024,0.689830
3,COK,cok/adapted,semi/cok,3,1,0,0.547373,0.656394
1,CCOT,ccot/format-thought,semi/ccot,3,1,0,0.036409,0.052465